name: On Merge Workflow

on: 
  pull_request:
    types: closed
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy / Develop
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
    secrets: inherit

  deploy-prod:
    name: Deploy / Prod
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
    secrets: inherit