name: On Merge Workflow

on: 
  pull_request:
    types: closed
    branches:
      - main
      - develop

jobs:
  deploy-prod:
    name: Deploy / Prod
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
    secrets: inherit